name: i2pi2p
version: '0.9.50'
summary: Invisible Internet Project (I2P) - anonymous network
description: |
  I2P is an anonymizing network, offering a simple layer that identity-sensitive
  applications can use to securely communicate. All data is wrapped with several
  layers of encryption, and the network is both distributed and dynamic, with no
  trusted parties.
  
  This is an unofficial Snap maintained by I2P contributor idk. It tracks the latest
  release of the I2P Java Reference Implementation.

  To install it, use `sudo snap install i2pi2p``

confinement: strict
base: core20

parts:
  i2pi2p:
    plugin: make
    source: https://github.com/eyedeekay/I2P-Snaps-and-Appimages.git
    source-branch: master
    override-build: |
      wget https://github.com/eyedeekay/I2P-Snaps-and-Appimages/releases/download/pre-0.9.50/profile.tar.gz
      tar -xvf profile.tar.gz
      cp -rv profile/* $SNAPCRAFT_PART_INSTALL
#    override-install: |
    build-packages:
      - openjdk-14-jdk
      - libjetty9-java
      - libtaglibs-standard-jstlel-java
      - libtomcat9-java
      - bash-completion
      - gettext
      - libgetopt-java
      - libjson-simple-java
      - libgmp-dev
      - libservice-wrapper-java
      - po-debconf
      - libc6-i386
      - adduser
      - apparmor
      - libjbigi-jni
      - lsb-base
      - service-wrapper
      - ucf
      - tar
      - expect
      - git
      - nsis
      - jq
      - curl
      - dos2unix
      - make
      - ant
      - wget
      - checkinstall

apps:
  i2pi2p:
    command: i2pbrowser.sh
    environment: 
      I2PROUTER: $SNAPCRAFT_PART_INSTALL/I2P/bin/I2P
    plugs:
      - home
      - network
      - network-bind
      - firewall-control
