name: i2pi2p
version: '0.9.47'
summary: Invisible Internet Project (I2P) - anonymous network
description: |
  I2P is an anonymizing network, offering a simple layer that identity-sensitive
  applications can use to securely communicate. All data is wrapped with several
  layers of encryption, and the network is both distributed and dynamic, with no
  trusted parties.
  
  This is an unofficial Snap maintained by I2P contributor idk. It tracks the latest
  release of the I2P Java Reference Implementation.

  To install it, use `sudo snap install i2pi2p`

  To run it, use `/snap/i2pi2p/current/runplain.sh`

confinement: strict
base: core20

parts:
  i2pi2p:
    plugin: make
    source: https://github.com/i2p/I2P-Snapps-and-Appimages.git
    source-tag: i2p-$SNAPCRAFT_PROJECT_VERSION
    override-build: |
      ./build.sh
      apt install -y ./*.deb
    build-packages:
      - default-jdk
      - libjetty9-java
      - libtaglibs-standard-jstlel-java
      - libtomcat9-java
      - bash-completion
      - gettext
      - libgetopt-java
      - libjson-simple-java
      - libgmp-dev
      - libservice-wrapper-java
      - po-debconf
      - libc6-i386
      - adduser
      - apparmor
      - libjbigi-jni
      - lsb-base
      - service-wrapper
      - ucf
      - tar
      - expect
      - git
      - nsis
      - jq
      - curl
      - dos2unix
      - make

apps:
  i2pi2p:
    command: /opt/i2p/bin/I2P
    plugs:
      - home
      - network
      - network-bind
      - firewall-control
