
name: Java CI

on: [push]

jobs:

  buildsnap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: |
          sudo apt-get update
          sudo apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext
      - name: build with script
        run: ./deb.sh
      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          name: i2p.firefox/i2p-bundle_*_amd64.deb
          path: i2p-bundle_amd64.deb
