
name: Java CI

on: [push]

jobs:

  builddeb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext libxcb1-dev openjdk-21-jdk libxau-dev libjpeg-dev libx11-dev libxi-dev libasound-dev libfuse-dev
          sudo update-java-alternatives --set java-1.21.0-openjdk-amd64
      - name: build with script
        run: ./deb.sh
      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          path: i2p.firefox/i2p-bundle_*_amd64.deb
          name: i2p-bundle_amd64.deb
      - name: build with script
        run: ./appimage.sh
      - name: Upload .AppImage
        uses: actions/upload-artifact@v4
        with:
          path: i2p.AppImage
          name: i2p.AppImage
      - run: cp -v i2p.firefox/i2p-bundle_*_amd64.deb i2pi2p/i2p-bundle_amd64.deb
      - run: ls i2pi2p
      - uses: snapcore/action-build@v1
        with:
          path: i2pi2p
          snapcraft-args: --verbose
      - run: find /home/runner/.local/state/snapcraft/log/ -exec cat {} \;
      - run: find . -name '*.snap'
      - name: Upload .snap
        uses: actions/upload-artifact@v4
        with:
          path: ./i2pi2p/i2pi2p_*_amd64.snap
          name: i2p-bundle_amd64.snap
