
name: Java CI

on: [push]

jobs:

  builddeb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: |
          sudo apt-get update
          sudo apt-get install -y nsis nsis-common nsis-pluginapi wget dos2unix curl jq gpg gettext
      - name: build with script
        run: ./deb.sh
      - name: Upload .deb
        uses: actions/upload-artifact@v4
        with:
          path: i2p.firefox/i2p-bundle_*_amd64.deb
          name: i2p-bundle_amd64.deb

  buildrpm:
    runs-on: ubuntu-latest
    container: fedora
    steps:
      - name: dependencies
        run: sudo yum install -y gettext golang-go git ant jq wget curl gpg xz ca-certificates rpm-build dos2unix
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - run: echo [Adoptium] >> /etc/yum.repos.d/adoptium.repo 
      - run: echo name=Adoptium >> /etc/yum.repos.d/adoptium.repo
      - run: . /etc/os-release; echo baseurl=https://packages.adoptium.net/artifactory/rpm/fedora/$VERSION_ID/x86_64/ >> /etc/yum.repos.d/adoptium.repo
      - run: echo enabled=1 >> /etc/yum.repos.d/adoptium.repo
      - run: echo gpgcheck=1 >> /etc/yum.repos.d/adoptium.repo
      - run: echo gpgkey=https://packages.adoptium.net/artifactory/api/gpg/key/public >> /etc/yum.repos.d/adoptium.repo
      - run: dnf clean all && rm -r /var/cache/dnf  && dnf upgrade -y && dnf update -y
      - run: dnf install -y temurin-21-jdk
      - name: build with script
        run: ./rpm.sh
      - name: Upload .rpm
        uses: actions/upload-artifact@v4
        with:
          path: i2p.firefox/i2p-bundle*.rpm
          name: i2p-bundle_amd64.rpm
